// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa1U4C0vFD5LRkMoMwZxaaPHD3h7U8bWo',
    appId: '1:250489968199:web:4867d8aee1326c370e8362',
    messagingSenderId: '250489968199',
    projectId: 'predoc-75853',
    authDomain: 'predoc-75853.firebaseapp.com',
    storageBucket: 'predoc-75853.firebasestorage.app',
    measurementId: 'G-N6FQGEBMEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjxTpfmYUoISVr8dhfmLx3jZf0vKXMBpk',
    appId: '1:250489968199:android:5eae6e0db73c31470e8362',
    messagingSenderId: '250489968199',
    projectId: 'predoc-75853',
    storageBucket: 'predoc-75853.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApLzmtk89V9wnAYVEPH133pe6eQ5mY-AU',
    appId: '1:250489968199:ios:5f6c4705bbc834bb0e8362',
    messagingSenderId: '250489968199',
    projectId: 'predoc-75853',
    storageBucket: 'predoc-75853.firebasestorage.app',
    iosClientId: '250489968199-nn835jd8o023p2j5ja600h9sar8rsaol.apps.googleusercontent.com',
    iosBundleId: 'com.predoc.predoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa1U4C0vFD5LRkMoMwZxaaPHD3h7U8bWo',
    appId: '1:250489968199:web:31720f67c421849d0e8362',
    messagingSenderId: '250489968199',
    projectId: 'predoc-75853',
    authDomain: 'predoc-75853.firebaseapp.com',
    storageBucket: 'predoc-75853.firebasestorage.app',
    measurementId: 'G-TTSSNG6Z31',
  );
}
